export const CREATE_NEW_TODO_LIST='CREATE_NEW_TODO_LIST';
export const ADD_ITEM='ADD_ITEM'
export const EDIT_ITEM='EDIT_ITEM'
export const DELETE_ITEM='DELETE_ITEM'
export const DELETE_LIST='DELETE_LIST'

